version: '3.9'

services:

  app:
    container_name: app
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./
        target: /home/app
    ports:
      - 18080:8080
    depends_on:
      - db
    tty: true

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - type: bind
        source: ./docker/db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
      # - type: volume
      #   source: db-data
      #   target: /var/lib/postgresql/data
    ports:
      - 15432:5432
    tty: true

volumes:
  db-data: